### PR TITLE
copy-hours-to-therp

### PR DESCRIPTION
**Pull request by Hayyan-Ebrahem**
@thomaspaulb

### CODE REVIEW

**Comment by Hayyan-Ebrahem** [comment]
@thomaspaulb  we need a test , coz the previous code gives "issue_id=235" a remote of "remote_id=235" this because of " remote_id = issue_trans.get(issue_id, issue_id)" and it creates a record in " therp.hr.analytic.timesheet " 
There is new issue in our system but its not assigned yet, after you assigned and it get registered in "SIFT.hr.analytic.timesheet" this code should pick it up

**Comment by Hayyan-Ebrahem** [comment]
@thomaspaulb I need permission to delete issue , "copy-issue-from-therp" as is doesn't check for project status "open" (i will fix it) it creates new issues (old date,status=closed) so some issues need to be deleted

**Comment by thomaspaulb** [comment]
You have permission to delete issue if you just use my login details like
you are using in the script:)

Op 13 jan. 2018 23:50 schreef "Hayyan-Ebrahem" <notifications@github.com>:

**Comment by Hayyan-Ebrahem** [comment]
@thomaspaulb well.. I did try it but didn't work :)

**Pull request merged**
